@host=https://3001-aqua-rodent-ndwiw5ni.ws-us11.gitpod.io/api


### Creación de hash
POST {{host}}/hash
Content-Type: application/json


### REGISTER
POST {{host}}/register
Content-Type: application/json

{
    "email":"hola@conejito.cl",
    "password":"1234",
    "username":"conejito"
}

# {
#     "email":"la@guagua.cl",
#     "password":"87654321",
#     "username":"guagua"
# }




###  @AUTH
# @name authSession
POST {{host}}/login
Content-Type: application/json

{
    "email":"hola@ortega.cl",
    "password":"87654321"
}

###
@token = {{authSession.response.body.$.token}}



### USER
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

